# -*- yaml -*-
project:
  type: website
  output-dir: _site
  render:
    - docs/index.qmd
    - rnn/lectures/index.qmd
    - rnn/labs/alphabet.qmd
    - rnn/labs/airplanes.qmd

institute: NBIS
format:
  nbis-quarto-revealjs:
    theme:
      - default
    date: last-modified
    date-format: "DD-MMM-YYYY"
    embed-resources: false
    code-line-numbers: false
    center: false
    toc: true
    toc-depth: 1
    slide-level: 2
    slide-number: true
    preview-links: true
    chalkboard: false
    smaller: true
    highlight-style: gruvbox
    fig-height: 12
    fig-width: 10
    fig-align: center
    text-align: left
    width: 1280
    height: 720
    margin: 0.1
    navigation-mode: vertical
    reference-location: margin
    ultitle: true

execute:
  echo: false
  warning: false
  cache: true
  include: true
  autodep: true
  eval: true
  error: true

extensions:
  - nbis-quarto
