# -*- yaml -*-
# Render slides
project:
  render:
    - rnn/lectures/index.qmd
    - basics/pytorch_intro/introduction_to_pytorch_1.md
    - basics/pytorch_intro/introduction_to_pytorch_2.md
    - good_practices/good_practices_project_design.md
    - cnn/lectures/CNN_lecture_1_classification.qmd
    - cnn/lectures/CNN_lecture_2_segmentation.qmd
    - representation_learning/index.qmd
